### ISSUE TITLE
SIG-Build 11/30 release notes

### ISSUE THREAD

**Issue by Ulrick28** [o3de/sig-build#12]
Please fill any info related to the below for the 11/30 release notes: Note this has a due date of Friday Nov 12th, 2021

 * Features
 * Bug fixes (GHI list if possible)
 * Deprecations
 * Known issues

**Comment by Ulrick28** [comment]
Installer/Project Manager
-	Better detection of whether a build fails when building through Project Manager
-	Link to view log while building
-	Showing the build button for projects that need to be rebuilt after a restart of Project Manager
-	Progress bars when deleting and cloning projects
-	Fix text being cut off incorrectly in multiple places in the Gem Catalog
-	Fixed lots of multiple of the same category appearing in the Gem Catalog
-	Fix some instances where building with Project Manager would take a long time with an install build

**Comment by AMZN-alexpete** [comment]
**Project Manager**

Features

- Can now create a project-specific Editor desktop shortcut from each project's menu. (Windows only)
- Can open CMake-GUI from each project's menu and from the project's Build button, pre-filled with the paths for that project.
- Project Manager will now prompt to get and setup Python on start up if Python is not found.
- Engine Name, version and path now visible in Engine Settings.
- Gem Catalog shows notifications when Gems and their dependencies are added or removed.
- Gem Catalog shows Gem dependencies.
- Gem Catalog notifies you when removing a Gem will also remove Gem dependencies.
- Project path automatically updates based on project name text input field.
- External Gems can now be added from the Gem Catalog.
- Project Manager logs output to the .o3de/Logs folder.

Fixes

- Project Manager window cannot be resized on Mac and Linux.
- Project Manager window too large for screens under 800 pixels tall. [#3946](https://github.com/o3de/o3de/issues/3946)
- Project Manager window background transparent on Mac.
- "Edit Project Settings" menu does not support projects with spaces in the project path
- Cannot type in "Project Location" field.
- Crash when Python not found or misconfigured.
- Quantity of Gems showed is not automatically updated in Project Manager [#4074](https://github.com/o3de/o3de/issues/4074)
- Registered external Gems do not show up in Configure Gems when creating a project [#1965](https://github.com/o3de/o3de/issues/1965)

**Comment by tonybalandiuk** [comment]
can this be closed?
