### ISSUE TITLE
Sig-Build:Need Infrastructure in place for 22.05.0 stabilization branch (need by EOD 4/4)

### ISSUE THREAD

**Issue by Ulrick28** [o3de/sig-build#26]
We (sig-release) are cutting the stabilization branch on 4/4. By EOD 4/4 we will need the appropriate AR and build infrastructure setup for the branch. We will also need appropriately signed nightly installer builds setup as well.

**Comment by amzn-changml** [comment]
Stubbed out the nightly installer and nightly AR build jobs in Jenkins. Will be creating the AR job once we cut the stabilization branch.

**Comment by amzn-changml** [comment]
AR Job auto created here: https://jenkins.build.o3de.org/job/O3DE/job/stabilization%252F2205/
Nightly Installer job here: https://jenkins.build.o3de.org/view/Tools/job/O3DE-stablization_2205_nightly-installer/
