### ISSUE TITLE
Proposed SIG-Build meeting agenda for June-29-2022

### ISSUE THREAD

**Issue by lmbr-pip** [o3de/sig-build#47]
## Meeting Details

- **Date/Time:** June 29, 2022 @ 05:00 pm UTC / 10:00 am PDT
- **Location:** [Discord SIG-Build Voice Room](https://discord.gg/wDNAQmatpq)
- **Moderator:** @amzn-changml 
- **Note Taker** TBD

The [SIG-Build Meetings](https://github.com/o3de/sig-build/tree/main/meetings) repo contains the history past calls, including a link to the agenda, recording, notes, and resources.

## SIG Updates

Notes from last meeting on June 15th: https://github.com/o3de/sig-build/blob/main/meetings/notes/sig-meeting-20220615.md

Brian - Followup on the GHI on mac and ios builds for nightly with shirang 

Shirang - Comment on the RFC for intermittent tests on any existing work from sig-build and reach out to sean on periodic build failure concerns 

Brian - Update Github PR RFC following feedback

## Meeting Agenda

- Discuss agenda from proposed topics
  - Build failure RCA improvement RFC - https://github.com/o3de/sig-build/pull/48
  - Intermittent Tests RFC needs a review from Build-SIG - https://github.com/o3de/sig-testing/issues/43
  - Proposed RFC - GitHub PR Workflow https://github.com/o3de/sig-build/issues/44 
  - Triage the new issues in the queue - https://github.com/o3de/o3de/issues?q=is%3Aissue+is%3Aopen+label%3Asig%2Fbuild+label%3Aneeds-triage+no%3Aassignee. 

## Outcomes from Discussion topics

**Discuss outcomes from agenda**

## Action Items

**Create actionable items from proposed topics**

## Open Discussion Items

List any additional items below!

**Comment by lmbr-pip** [comment]
* Discuss SIG/Build ownership of the installers. Discuss concerns raised in https://github.com/o3de/community/pull/136

**Comment by amzn-changml** [comment]
PR for numpy update raised by Dependabot: https://github.com/o3de/o3de/pull/10281

In addition, we've addressed 3 CVE items in the past week:

https://github.com/o3de/o3de/pull/9863 - Bump numpy from 1.18.1 to 1.21.0 in /python
https://github.com/o3de/o3de/pull/10005 - Bump pillow from 9.1.0 to 9.1.1 in /python
https://github.com/o3de/o3de/pull/10162 - Bump jinja2 from 2.11.2 to 2.11.3 in /python
