### ISSUE TITLE
Roadmap Item - Stabilization PR checklist automation

### ISSUE THREAD

**Issue by amzn-changml** [o3de/sig-build#96]
### Summary:
@o3de/sig-release would like to have a automation that can show the [Exception checklist](https://github.com/o3de/sig-release/blob/main/releases/Process/O3DE%20Exception%20Checklist.md?rgh-link-date=2023-07-08T22%3A03%3A20Z) whenever someone creates a PR into the stabilization branch and only can be merged if these SIG approved (based on the checklist)

- UX SIG representative (chair/cochair)
- Testing SIG representative (chair/cochair)
- The code maintainers
- Release Manager or co-Release Manager.

### What is the relevance of this feature?
- Reminds contributors to follow a predefined checklist when creating a PR to stabilization

```[tasklist]
### Tasks
- [x] Investigate post PR creation automation to create a checklist for stabilization submissions
- [x] Implement an PR checklist automation solution
```

**Comment by Ulrick28** [comment]
We will need to revisit the checklist as we aren't sure if sig-testing or UX makes sense as requirements going forward. I'll follow up with both sigs.

**Comment by amzn-changml** [comment]
Automation deployed. Closing issue
